#include "GameMap.h"

CGameMap::CGameMap()
{
	m_bitmap_road = NULL;
	m_bitmap_redbrick=NULL;
	m_bitmap_redhouse=NULL;
	m_bitmap_yellowbrick=NULL;
	m_bitmap_yellowhouse=NULL;
	m_bitmap_tree=NULL;
	m_bitmap_box=NULL;
	m_bitmap_bluehouse=NULL;
}


CGameMap::~CGameMap()
{
	DeleteObject(m_bitmap_road);
	DeleteObject(m_bitmap_redbrick);
	DeleteObject(m_bitmap_redhouse);
	DeleteObject(m_bitmap_yellowbrick);
	DeleteObject(m_bitmap_yellowhouse);
	DeleteObject(m_bitmap_tree);
	DeleteObject(m_bitmap_box);
	DeleteObject(m_bitmap_bluehouse);
	m_bitmap_road = NULL;
	m_bitmap_redbrick=NULL;
	m_bitmap_redhouse=NULL;
	m_bitmap_yellowbrick=NULL;
	m_bitmap_yellowhouse=NULL;
	m_bitmap_tree=NULL;
	m_bitmap_box=NULL;
	m_bitmap_bluehouse=NULL;
}

void CGameMap::MapInit(HINSTANCE hIns)
{
	m_bitmap_road = LoadBitmap(hIns,MAKEINTRESOURCE(IDB_ROAD));
	m_bitmap_redbrick = LoadBitmap(hIns,MAKEINTRESOURCE(IDB_redbrick));
	m_bitmap_redhouse = LoadBitmap(hIns,MAKEINTRESOURCE(IDB_redhouse));
	m_bitmap_yellowbrick = LoadBitmap(hIns,MAKEINTRESOURCE(IDB_yellowbrick));
	m_bitmap_yellowhouse = LoadBitmap(hIns,MAKEINTRESOURCE(IDB_yellowhouse));
	m_bitmap_tree = LoadBitmap(hIns,MAKEINTRESOURCE(IDB_tree));
	m_bitmap_box = LoadBitmap(hIns,MAKEINTRESOURCE(IDB_box));
	m_bitmap_bluehouse = LoadBitmap(hIns,MAKEINTRESOURCE(IDB_bluehouse));
}

void CGameMap::MapShow(HDC hdc)
{
	HDC hdcMem = CreateCompatibleDC(hdc);
	SelectObject(hdcMem,m_bitmap_road);
	BitBlt(hdc,20,41,800,600,hdcMem,0,0,SRCCOPY);
	int x,y=0;//x，y记录每次加载不同图片位置的坐标
	for(int i=1;i<13;i++)
	{
		for(int j=1;j<16;j++)
		{
			x = (j-1) * 40 +20;
			y = (i-1) * 44 +41;

			if(i==1)//第一至十二行逐行加载图片
			{
				if(j==2)
				{
					SelectObject(hdcMem,m_bitmap_redhouse);
					TransparentBlt(hdc,x,y-13,40,57,hdcMem,0,0,40,57,RGB(255,0,255));
				}
				if(j==3)
				{
					SelectObject(hdcMem,m_bitmap_redbrick);
					BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);

				}
				if(j==4)
				{
					SelectObject(hdcMem,m_bitmap_redhouse);
					TransparentBlt(hdc,x,y-13,40,57,hdcMem,0,0,40,57,RGB(255,0,255));
				}
				if(j==5)
				{
					SelectObject(hdcMem,m_bitmap_redbrick);
					BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);


				}
				if(i==1&&j==6)
				{
					SelectObject(hdcMem,m_bitmap_tree);
					TransparentBlt(hdc,x,y-23,40,67,hdcMem,0,0,40,67,RGB(255,0,255));
				}
				if(i==1&&j==8)
				{
					SelectObject(hdcMem,m_bitmap_tree);
					TransparentBlt(hdc,x,y-23,40,67,hdcMem,0,0,40,67,RGB(255,0,255));

				}
				if(j==10)
				{
					SelectObject(hdcMem,m_bitmap_tree);
					TransparentBlt(hdc,x,y-23,40,67,hdcMem,0,0,40,67,RGB(255,0,255));

				}
				if(j==11)
				{
					SelectObject(hdcMem,m_bitmap_redbrick);
					BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);
				}
				if(j==12)
				{
					SelectObject(hdcMem,m_bitmap_bluehouse);
					TransparentBlt(hdc,x,y-13,40,57,hdcMem,0,0,40,57,RGB(255,0,255));
				}
				if(j==13)
				{
					SelectObject(hdcMem,m_bitmap_redbrick);
					BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);
				}
				if(j==14)
				{
					SelectObject(hdcMem,m_bitmap_bluehouse);
					TransparentBlt(hdc,x,y-13,40,57,hdcMem,0,0,40,57,RGB(255,0,255));
				}

			}
			if(i==2)
			{
				if(j==3)
				{
					SelectObject(hdcMem,m_bitmap_yellowbrick);
					BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);
				}
				if(j==4)
				{
					SelectObject(hdcMem,m_bitmap_redbrick);
					BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);
				}
				if(j==5)
				{
					SelectObject(hdcMem,m_bitmap_yellowbrick);
					BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);
				}
				if(j==6)
				{
					SelectObject(hdcMem,m_bitmap_redbrick);
					BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);
				}
				if(j==10)
				{
					SelectObject(hdcMem,m_bitmap_redbrick);
					BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);
				}
				if(j==11)
				{
					SelectObject(hdcMem,m_bitmap_yellowbrick);
					BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);
				}
				if(j==12)
				{
					SelectObject(hdcMem,m_bitmap_redbrick);
					BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);
				}
				if(j==13)
				{
					SelectObject(hdcMem,m_bitmap_yellowbrick);
					BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);
				}
			}

			if(i==3)
			{
				if(j==2)
				{
					SelectObject(hdcMem,m_bitmap_redhouse);
					TransparentBlt(hdc,x,y-13,40,57,hdcMem,0,0,40,57,RGB(255,0,255));
				}

				if(j==3)
				{
					SelectObject(hdcMem,m_bitmap_redbrick);
					BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);
				}
				if(j==4)
				{
					SelectObject(hdcMem,m_bitmap_redhouse);
					TransparentBlt(hdc,x,y-13,40,57,hdcMem,0,0,40,57,RGB(255,0,255));
				}

				if(j==5)
				{
					SelectObject(hdcMem,m_bitmap_redbrick);
					BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);
				}
				if(j==6)
				{
					SelectObject(hdcMem,m_bitmap_tree);
					TransparentBlt(hdc,x,y-23,40,67,hdcMem,0,0,40,67,RGB(255,0,255));
				}
				if(j==7)
				{
					SelectObject(hdcMem,m_bitmap_box);
					BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);
				}
				if(j==8)
				{
					SelectObject(hdcMem,m_bitmap_tree);
					TransparentBlt(hdc,x,y-23,40,67,hdcMem,0,0,40,67,RGB(255,0,255));
				}
				if(j==9)
				{
					SelectObject(hdcMem,m_bitmap_box);
					BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);
				}
				if(j==10)
				{
					SelectObject(hdcMem,m_bitmap_redbrick);
					BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);
				}
				if(j==11)
				{
					SelectObject(hdcMem,m_bitmap_bluehouse);
					TransparentBlt(hdc,x,y-13,40,57,hdcMem,0,0,40,57,RGB(255,0,255));
				}
				if(j==12)
				{
					SelectObject(hdcMem,m_bitmap_redbrick);
					BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);
				}
				if(j==13)
				{
					SelectObject(hdcMem,m_bitmap_bluehouse);
					TransparentBlt(hdc,x,y-13,40,57,hdcMem,0,0,40,57,RGB(255,0,255));
				}
			}
			if(i==4)
			{
				if(j==1)
				{
					SelectObject(hdcMem,m_bitmap_yellowbrick);
					BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);
				}
				if(j==2)
				{
					SelectObject(hdcMem,m_bitmap_redbrick);
					BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);
				}
				if(j==3)
				{
					SelectObject(hdcMem,m_bitmap_yellowbrick);
					BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);
				}
				if(j==4)
				{
					SelectObject(hdcMem,m_bitmap_redbrick);
					BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);
				}
				if(j==5)
				{
					SelectObject(hdcMem,m_bitmap_tree);
					TransparentBlt(hdc,x,y-23,40,67,hdcMem,0,0,40,67,RGB(255,0,255));
				}
				if(j==6)
				{
					SelectObject(hdcMem,m_bitmap_box);
					BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);
				}
				if(j==7)
				{
					SelectObject(hdcMem,m_bitmap_box);
					BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);
				}
				if(j==8)
				{
					SelectObject(hdcMem,m_bitmap_redbrick);
					BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);
				}
				if(j==9)
				{
					SelectObject(hdcMem,m_bitmap_box);
					BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);
				}
				if(j==10)
				{
					SelectObject(hdcMem,m_bitmap_box);
					BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);
				}
				if(j==9)
				{
					SelectObject(hdcMem,m_bitmap_tree);
					TransparentBlt(hdc,x,y-23,40,67,hdcMem,0,0,40,67,RGB(255,0,255));
				}
				if(j==10)
				{
					SelectObject(hdcMem,m_bitmap_redbrick);
					BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);
				}
				if(j==11)
				{
					SelectObject(hdcMem,m_bitmap_yellowbrick);
					BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);
				}
				if(j==12)
				{
					SelectObject(hdcMem,m_bitmap_redbrick);
					BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);
				}
				if(j==13)
				{
					SelectObject(hdcMem,m_bitmap_yellowbrick);
					BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);
				}
			}
			if(i==5)
			{
				if(j==1)
				{
					SelectObject(hdcMem,m_bitmap_redbrick);
					BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);
				}
				if(j==2)
				{
					SelectObject(hdcMem,m_bitmap_tree);
					TransparentBlt(hdc,x,y-23,40,67,hdcMem,0,0,40,67,RGB(255,0,255));
				}
				if(j==3)
				{
					SelectObject(hdcMem,m_bitmap_redbrick);
					BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);
				}
				if(j==4)
				{
					SelectObject(hdcMem,m_bitmap_tree);
					TransparentBlt(hdc,x,y-23,40,67,hdcMem,0,0,40,67,RGB(255,0,255));
				}
				if(j==5)
				{
					SelectObject(hdcMem,m_bitmap_box);
					BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);
				}
				if(j==6)
				{
					SelectObject(hdcMem,m_bitmap_box);
					BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);
				}
				if(j==7)
				{
					SelectObject(hdcMem,m_bitmap_tree);
					TransparentBlt(hdc,x,y-23,40,67,hdcMem,0,0,40,67,RGB(255,0,255));
				}
				if(j==9)
				{
					SelectObject(hdcMem,m_bitmap_tree);
					TransparentBlt(hdc,x,y-23,40,67,hdcMem,0,0,40,67,RGB(255,0,255));
				}
				if(j==10)
				{
					SelectObject(hdcMem,m_bitmap_box);
					BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);
				}
				if(j==11)
				{
					SelectObject(hdcMem,m_bitmap_box);
					BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);
				}
				if(j==12)
				{
					SelectObject(hdcMem,m_bitmap_tree);
					TransparentBlt(hdc,x,y-23,40,67,hdcMem,0,0,40,67,RGB(255,0,255));
				}
				if(j==13)
				{
					SelectObject(hdcMem,m_bitmap_redbrick);
					BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);
				}
				if(j==14)
				{
					SelectObject(hdcMem,m_bitmap_tree);
					TransparentBlt(hdc,x,y-23,40,67,hdcMem,0,0,40,67,RGB(255,0,255));
				}
				if(j==15)
				{
					SelectObject(hdcMem,m_bitmap_redbrick);
					BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);
				}
			}
			if(i==6)
			{
				if(j==1)
				{
					SelectObject(hdcMem,m_bitmap_yellowbrick);
					BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);
				}
				if(j==3)
				{
					SelectObject(hdcMem,m_bitmap_box);
					BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);
				}
				if(j==6)
				{
					SelectObject(hdcMem,m_bitmap_tree);
					TransparentBlt(hdc,x,y-23,40,67,hdcMem,0,0,40,67,RGB(255,0,255));
				}
				if(j==7)
				{
					SelectObject(hdcMem,m_bitmap_redbrick);
					BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);
				}
				if(j==9)
				{
					SelectObject(hdcMem,m_bitmap_redbrick);
					BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);
				}
				if(j==10)
				{
					SelectObject(hdcMem,m_bitmap_tree);
					TransparentBlt(hdc,x,y-23,40,67,hdcMem,0,0,40,67,RGB(255,0,255));
				}
				if(j==13)
				{
					SelectObject(hdcMem,m_bitmap_box);
					BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);
				}
				if(j==15)
				{
					SelectObject(hdcMem,m_bitmap_yellowbrick);
					BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);
				}
			}
			if(i==7)
			{
				if(j==1)
				{
					SelectObject(hdcMem,m_bitmap_yellowbrick);
					BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);
				}
				if(j==2)
				{
					SelectObject(hdcMem,m_bitmap_tree);
					TransparentBlt(hdc,x,y-23,40,67,hdcMem,0,0,40,67,RGB(255,0,255));
				}
				if(j==3)
				{
					SelectObject(hdcMem,m_bitmap_redbrick);
					BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);
				}
				if(j==4)
				{
					SelectObject(hdcMem,m_bitmap_tree);
					TransparentBlt(hdc,x,y-23,40,67,hdcMem,0,0,40,67,RGB(255,0,255));
				}
				if(j==6)
				{
					SelectObject(hdcMem,m_bitmap_yellowbrick);
					BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);
				}
				if(j==10)
				{
					SelectObject(hdcMem,m_bitmap_yellowbrick);
					BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);
				}
				if(j==12)
				{
					SelectObject(hdcMem,m_bitmap_tree);
					TransparentBlt(hdc,x,y-23,40,67,hdcMem,0,0,40,67,RGB(255,0,255));
				}
				if(j==13)
				{
					SelectObject(hdcMem,m_bitmap_redbrick);
					BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);
				}
				if(j==14)
				{
					SelectObject(hdcMem,m_bitmap_tree);
					TransparentBlt(hdc,x,y-23,40,67,hdcMem,0,0,40,67,RGB(255,0,255));
				}
				if(j==15)
				{
					SelectObject(hdcMem,m_bitmap_yellowbrick);
					BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);
				}
			}
			if(i==8)
			{
				if(j==1)
				{
					SelectObject(hdcMem,m_bitmap_yellowbrick);
					BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);
				}
				if(j==3)
				{
					SelectObject(hdcMem,m_bitmap_box);
					BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);
				}
				if(j==6)
				{
					SelectObject(hdcMem,m_bitmap_tree);
					TransparentBlt(hdc,x,y-23,40,67,hdcMem,0,0,40,67,RGB(255,0,255));
				}
				if(i==9)
				{
					if(j==1)
					{
						SelectObject(hdcMem,m_bitmap_yellowbrick);
						BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);
					}
					if(j==3)
					{
						SelectObject(hdcMem,m_bitmap_box);
						BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);
					}
					if(j==6)
					{
						SelectObject(hdcMem,m_bitmap_tree);
						TransparentBlt(hdc,x,y-23,40,67,hdcMem,0,0,40,67,RGB(255,0,255));
					}
					if(j==7)
					{
						SelectObject(hdcMem,m_bitmap_redbrick);
						BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);
					}
					if(j==8)
					{
						SelectObject(hdcMem,m_bitmap_redbrick);
						BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);
					}
					if(j==9)
					{
						SelectObject(hdcMem,m_bitmap_redbrick);
						BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);
					}
					if(j==10)
					{
						SelectObject(hdcMem,m_bitmap_tree);
						TransparentBlt(hdc,x,y-23,40,67,hdcMem,0,0,40,67,RGB(255,0,255));
					}
					if(j==13)
					{
						SelectObject(hdcMem,m_bitmap_box);
						BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);
					}
					if(j==15)
					{
						SelectObject(hdcMem,m_bitmap_yellowbrick);
						BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);
					}
				}
				if(j==9)
				{
					SelectObject(hdcMem,m_bitmap_redbrick);
					BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);
				}
				if(j==10)
				{
					SelectObject(hdcMem,m_bitmap_tree);
					TransparentBlt(hdc,x,y-23,40,67,hdcMem,0,0,40,67,RGB(255,0,255));
				}
				if(j==13)
				{
					SelectObject(hdcMem,m_bitmap_box);
					BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);
				}
				if(j==15)
				{
					SelectObject(hdcMem,m_bitmap_yellowbrick);
					BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);
				}
			}
			if(i==9)
			{
				if(j==1)
				{
					SelectObject(hdcMem,m_bitmap_redbrick);
					BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);
				}
				if(j==2)
				{
					SelectObject(hdcMem,m_bitmap_tree);
					TransparentBlt(hdc,x,y-23,40,67,hdcMem,0,0,40,67,RGB(255,0,255));
				}
				if(j==3)
				{
					SelectObject(hdcMem,m_bitmap_redbrick);
					BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);
				}
				if(j==4)
				{
					SelectObject(hdcMem,m_bitmap_tree);
					TransparentBlt(hdc,x,y-23,40,67,hdcMem,0,0,40,67,RGB(255,0,255));
				}
				if(j==5)
				{
					SelectObject(hdcMem,m_bitmap_box);
					BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);
				}
				if(j==6)
				{
					SelectObject(hdcMem,m_bitmap_box);
					BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);
				}
				if(j==7)
				{
					SelectObject(hdcMem,m_bitmap_tree);
					TransparentBlt(hdc,x,y-23,40,67,hdcMem,0,0,40,67,RGB(255,0,255));
				}
				if(j==9)
				{
					SelectObject(hdcMem,m_bitmap_tree);
					TransparentBlt(hdc,x,y-23,40,67,hdcMem,0,0,40,67,RGB(255,0,255));
				}
				if(j==10)
				{
					SelectObject(hdcMem,m_bitmap_box);
					BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);
				}
				if(j==11)
				{
					SelectObject(hdcMem,m_bitmap_box);
					BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);
				}
				if(j==12)
				{
					SelectObject(hdcMem,m_bitmap_tree);
					TransparentBlt(hdc,x,y-23,40,67,hdcMem,0,0,40,67,RGB(255,0,255));
				}
				if(j==13)
				{
					SelectObject(hdcMem,m_bitmap_redbrick);
					BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);
				}
				if(j==14)
				{
					SelectObject(hdcMem,m_bitmap_tree);
					TransparentBlt(hdc,x,y-23,40,67,hdcMem,0,0,40,67,RGB(255,0,255));
				}
				if(j==15)
				{
					SelectObject(hdcMem,m_bitmap_redbrick);
					BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);
				}
			}
			if(i==10)
			{
				if(j==1)
				{
					SelectObject(hdcMem,m_bitmap_yellowbrick);
					BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);
				}
				if(j==2)
				{
					SelectObject(hdcMem,m_bitmap_redbrick);
					BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);
				}
				if(j==3)
				{
					SelectObject(hdcMem,m_bitmap_yellowbrick);
					BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);
				}
				if(j==4)
				{
					SelectObject(hdcMem,m_bitmap_redbrick);
					BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);
				}
				if(j==5)
				{
					SelectObject(hdcMem,m_bitmap_tree);
					TransparentBlt(hdc,x,y-23,40,67,hdcMem,0,0,40,67,RGB(255,0,255));
				}
				if(j==6)
				{
					SelectObject(hdcMem,m_bitmap_box);
					BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);
				}
				if(j==7)
				{
					SelectObject(hdcMem,m_bitmap_box);
					BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);
				}
				if(j==8)
				{
					SelectObject(hdcMem,m_bitmap_redbrick);
					BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);
				}
				if(j==9)
				{
					SelectObject(hdcMem,m_bitmap_box);
					BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);
				}
				if(j==10)
				{
					SelectObject(hdcMem,m_bitmap_box);
					BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);
				}
				if(j==9)
				{
					SelectObject(hdcMem,m_bitmap_tree);
					TransparentBlt(hdc,x,y-23,40,67,hdcMem,0,0,40,67,RGB(255,0,255));
				}
				if(j==10)
				{
					SelectObject(hdcMem,m_bitmap_redbrick);
					BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);
				}
				if(j==11)
				{
					SelectObject(hdcMem,m_bitmap_yellowbrick);
					BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);
				}
				if(j==12)
				{
					SelectObject(hdcMem,m_bitmap_redbrick);
					BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);
				}
				if(j==13)
				{
					SelectObject(hdcMem,m_bitmap_yellowbrick);
					BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);
				}
			}
			if(i==11)
			{
				if(j==2)
				{
					SelectObject(hdcMem,m_bitmap_redhouse);
					TransparentBlt(hdc,x,y-13,40,57,hdcMem,0,0,40,57,RGB(255,0,255));
				}

				if(j==3)
				{
					SelectObject(hdcMem,m_bitmap_redbrick);
					BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);
				}
				if(j==4)
				{
					SelectObject(hdcMem,m_bitmap_redhouse);
					TransparentBlt(hdc,x,y-13,40,57,hdcMem,0,0,40,57,RGB(255,0,255));
				}

				if(j==5)
				{
					SelectObject(hdcMem,m_bitmap_redbrick);
					BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);
				}
				if(j==6)
				{
					SelectObject(hdcMem,m_bitmap_tree);
					TransparentBlt(hdc,x,y-23,40,67,hdcMem,0,0,40,67,RGB(255,0,255));
				}
				if(j==7)
				{
					SelectObject(hdcMem,m_bitmap_box);
					BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);
				}
				if(j==8)
				{
					SelectObject(hdcMem,m_bitmap_tree);
					TransparentBlt(hdc,x,y-23,40,67,hdcMem,0,0,40,67,RGB(255,0,255));
				}
				if(j==9)
				{
					SelectObject(hdcMem,m_bitmap_box);
					BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);
				}
				if(j==10)
				{
					SelectObject(hdcMem,m_bitmap_redbrick);
					BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);
				}
				if(j==11)
				{
					SelectObject(hdcMem,m_bitmap_bluehouse);
					TransparentBlt(hdc,x,y-13,40,57,hdcMem,0,0,40,57,RGB(255,0,255));
				}
				if(j==12)
				{
					SelectObject(hdcMem,m_bitmap_redbrick);
					BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);
				}
				if(j==13)
				{
					SelectObject(hdcMem,m_bitmap_bluehouse);
					TransparentBlt(hdc,x,y-13,40,57,hdcMem,0,0,40,57,RGB(255,0,255));
				}
			}
			if(i==12)
			{
				if(j==2)
				{
					SelectObject(hdcMem,m_bitmap_redhouse);
					TransparentBlt(hdc,x,y-13,40,57,hdcMem,0,0,40,57,RGB(255,0,255));
				}
				if(j==3)
				{
					SelectObject(hdcMem,m_bitmap_redbrick);
					BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);

				}
				if(j==4)
				{
					SelectObject(hdcMem,m_bitmap_redhouse);
					TransparentBlt(hdc,x,y-13,40,57,hdcMem,0,0,40,57,RGB(255,0,255));
				}
				if(j==5)
				{
					SelectObject(hdcMem,m_bitmap_redbrick);
					BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);


				}
				if(i==1&&j==6)
				{
					SelectObject(hdcMem,m_bitmap_tree);
					TransparentBlt(hdc,x,y-23,40,67,hdcMem,0,0,40,67,RGB(255,0,255));
				}
				if(i==1&&j==8)
				{
					SelectObject(hdcMem,m_bitmap_tree);
					TransparentBlt(hdc,x,y-23,40,67,hdcMem,0,0,40,67,RGB(255,0,255));

				}
				if(j==10)
				{
					SelectObject(hdcMem,m_bitmap_tree);
					TransparentBlt(hdc,x,y-23,40,67,hdcMem,0,0,40,67,RGB(255,0,255));

				}
				if(j==11)
				{
					SelectObject(hdcMem,m_bitmap_redbrick);
					BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);
				}
				if(j==12)
				{
					SelectObject(hdcMem,m_bitmap_bluehouse);
					TransparentBlt(hdc,x,y-13,40,57,hdcMem,0,0,40,57,RGB(255,0,255));
				}
				if(j==13)
				{
					SelectObject(hdcMem,m_bitmap_redbrick);
					BitBlt(hdc,x,y,40,44,hdcMem,0,0,SRCCOPY);
				}
				if(j==14)
				{
					SelectObject(hdcMem,m_bitmap_bluehouse);
					TransparentBlt(hdc,x,y-13,40,57,hdcMem,0,0,40,57,RGB(255,0,255));
				}
			}
		}
	}
	DeleteDC(hdcMem);
}
